name: Consumer Project
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - run: cmake --version
      - run: python --version
      - run: pip install conan
      - run: mkdir ${{runner.workspace}}/consumer/build
        shell: bash
      - run: conan install ..
        working-directory: ${{runner.workspace}}/consumer/build
